app:
  title: bose's login study

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://49.50.175.185:3306/login
    username: bose
    password: qhs1tjd2
  # jpa 설정
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.show_sql: false
      hibernate.format_sql: true
